name: Greet Everyone
on:
  push:
    branches-ignore:
      master

jobs:
  infrastructure:
    name: Diff infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show infrastructure
        run: |
          cd infrastructure/aws

          npm install

          npm run build

          # todo: npm run cdk diff
          npm run cdk synth

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          node common/scripts/install-run-rush.js install

          # todo: iterate over services dir
          cd services/_test

          npm run build

          npm run test
